version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_DATABASE=teepon
      - MYSQL_ROOT_PASSWORD=rUb1c()n
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports: 
      - 5000:5000
    command: ./docker-entrypoint.sh
volumes:
  mysql-data:
