version: "3.8"

services:
  frontend:
    depends_on: 
      - backend
    build: ./frontend
    ports:
      - 3000:3000

  backend:
    build: ./backend
    ports: 
      - 5000:5000
    command: ./docker-entrypoint.sh
