"""6

Revision ID: 0a162a3d7757
Revises: 7a4a5bc43f87
Create Date: 2024-06-30 01:01:26.053376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a162a3d7757'
down_revision = '7a4a5bc43f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat',
    sa.Column('outing_id', sa.String(length=36), nullable=False),
    sa.Column('messages_id', sa.String(length=36), nullable=False),
    sa.Column('ai_messages_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ai_messages_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['messages_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['outing_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('outing_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_chat')
    # ### end Alembic commands ###
