"""3

Revision ID: 24d66d98663b
Revises: 82a896cb6068
Create Date: 2024-07-02 15:53:55.159411

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '24d66d98663b'
down_revision = '82a896cb6068'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('uid')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_index('uid', ['uid'], unique=True)

    # ### end Alembic commands ###
