"""7

Revision ID: 4dec3d6bb1c9
Revises: 0a162a3d7757
Create Date: 2024-07-02 02:06:30.540457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4dec3d6bb1c9'
down_revision = '0a162a3d7757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_chat_ai',
    sa.Column('outing_id', sa.String(length=36), nullable=False),
    sa.Column('ai_messages_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['ai_messages_id'], ['ai_messages.id'], ),
    sa.ForeignKeyConstraint(['outing_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('outing_id')
    )
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.drop_constraint('group_chat_ibfk_1', type_='foreignkey')
        batch_op.drop_column('ai_messages_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_messages_id', mysql.VARCHAR(length=36), nullable=False))
        batch_op.create_foreign_key('group_chat_ibfk_1', 'ai_messages', ['ai_messages_id'], ['id'])

    op.drop_table('group_chat_ai')
    # ### end Alembic commands ###
