"""1

Revision ID: 520310b0ab7e
Revises: 
Create Date: 2024-07-02 10:05:51.588135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520310b0ab7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('access_token', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('ai_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_from', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['send_from'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_from', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['send_from'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('latest_location', sa.String(length=240), nullable=True),
    sa.Column('outing_topic', sa.String(length=120), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ai_messages_group_id', sa.String(length=36), nullable=True),
    sa.Column('ai_message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ai_message_id'], ['ai_message.id'], ),
    sa.ForeignKeyConstraint(['ai_messages_group_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friend_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outing_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outing_id'], ['outing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('messages_group_id', sa.String(length=36), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['messages_group_id'], ['outing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('friend_list')
    op.drop_table('ai_messages')
    op.drop_table('outing')
    op.drop_table('message')
    op.drop_table('ai_message')
    op.drop_table('user')
    # ### end Alembic commands ###
